app:
  version_check_url: "https://raw.githubusercontent.com/sansan0/TrendRadar/master/version.txt"
  show_version_update: false

mode: current

save_result_to_repo: true

# 저장할 파일 경로
history_result_path: "result/history.json"
current_result_path: "result/current.json"
output_path: "docs"

# 플랫폼 설정
enable_platforms:
  - yahoo
  - cnn
  - buzzsumo
  - reddit

keyword_check_mode: or

keywords:
  - 미국
  - 테슬라
  - 비트코인
  - 엔비디아
  - 개발자
  - xbox
  - 삼성
  - 육아

enable_word_frequency_analysis: true
frequency_words_path: "config/frequency_words.txt"